### ISSUE TITLE
Parse and load ERDDAP datasets.xml enough to load Pandas dataframes and Xarray datasets from some dataset types

### ISSUE THREAD

**Issue by abkfenris** [gulfofmaine/dataset_catalog#3]
```[tasklist]
### Tasks
- [ ] https://github.com/gulfofmaine/dataset_catalog/issues/4
- [ ] https://github.com/gulfofmaine/dataset_catalog/issues/11
- [ ] https://github.com/gulfofmaine/dataset_catalog/issues/5
- [ ] https://github.com/gulfofmaine/dataset_catalog/issues/8
- [ ] https://github.com/gulfofmaine/dataset_catalog/issues/12
- [ ] https://github.com/gulfofmaine/dataset_catalog/issues/6
- [ ] https://github.com/gulfofmaine/dataset_catalog/issues/7
- [ ] https://github.com/gulfofmaine/dataset_catalog/issues/9
- [ ] https://github.com/gulfofmaine/dataset_catalog/issues/10
```
